name: Equinsight
favicon: null
layout_spectrum: 0.24271
typography_spectrum: 0.65312
title: "Unique insight into your horse's health"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72298419-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#88A0B0'
    - '#008080'
    - '#609898'
    - '#F80000'
    - '#000000'
  brandStrength: 0.7292255689390004
  lightness: 0.2407628963701427
  saturation: 0.4860698813572526
  rhythmicContrast: 0.0009546298533678055
purpose: []
